### PR TITLE
[master] RHCOS version should accept the specific os version

### PR DESCRIPTION
**Pull request by PanYaLian**
Signed-off-by: ylpan <ylpan@cn.ibm.com>

### CODE REVIEW

**Comment by jichenjc** [comment]
do we need any test case add for this?

**Comment by jichenjc** [comment]
I mean RHCOS4.3 with RHCOS43 ?

**Comment by PanYaLian** [comment]
> I mean RHCOS4.3 with RHCOS43 ?

Add test case

**Comment by PanYaLian** [comment]
[root@ruicos-185 python-zvm-sdk]# tox -epy36
py36 develop-inst-noop: /root/git/python-zvm-sdk
py36 installed: alabaster==0.7.12,attrs==19.3.0,Babel==2.8.0,certifi==2020.6.20,chardet==3.0.4,docutils==0.16,extras==1.0.0,fixtures==3.0.0,idna==2.10,imagesize==1.2.0,importlib-metadata==1.7.0,importlib-resources==2.0.1,Jinja2==2.11.2,jsonschema==3.2.0,linecache2==1.0.0,MarkupSafe==1.1.1,mock==4.0.2,netaddr==0.7.20,packaging==20.4,pbr==5.4.5,Pygments==2.6.1,PyJWT==1.7.1,pyparsing==2.4.7,pyrsistent==0.16.0,python-mimeparse==1.6.0,python-subunit==1.4.0,pytz==2020.1,PyYAML==5.3.1,repoze.lru==0.7,requests==2.24.0,Routes==2.4.1,six==1.15.0,snowballstemmer==2.0.0,Sphinx==3.1.1,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==1.0.3,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.4,testtools==2.4.0,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.25.9,WebOb==1.8.6,zipp==3.1.0,-e git+https://github.com/openmainframeproject/python-zvm-sdk.git@c3bc3c370b6b648709e35099f5b8e3ca45321737#egg=zVMCloudConnector
py36 run-test-pre: PYTHONHASHSEED='79789342'
py36 run-test: commands[0] | python -m unittest discover -v -s /root/git/python-zvm-sdk/zvmsdk/tests/unit
test_guest_capture (sdkclientcases.test_restclient.RESTClientTestCase) ... ok
test_guest_config_minidisks (sdkclientcases.test_restclient.RESTClientTestCase) ... ok
test_guest_create (sdkclientcases.test_restclient.RESTClientTestCase) ... ok
test_guest_create_disks (sdkclientcases.test_restclient.RESTClientTestCase) ... ok
test_guest_create_network_interface (sdkclientcases.test_restclient.RESTClientTestCase) ... ok
....................
test_guests_get_nic_info_with_vswitch (sdkwsgi.handlers.test_guest.HandlersGuestTest) ... ok
test_list (sdkwsgi.handlers.test_guest.HandlersGuestTest) ... ok
test_host_get_disk_info (sdkwsgi.handlers.test_host.HandlersHostTest) ... ok
test_host_get_guest_list (sdkwsgi.handlers.test_host.HandlersHostTest) ... ok
test_host_get_info (sdkwsgi.handlers.test_host.HandlersHostTest) ... ok
test_image_create (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
test_image_create_invalid_image_meta (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
test_image_create_invalid_image_meta_md5sum (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
test_image_create_invalid_os_version (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
**test_image_create_invalid_rhcos_os_version (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok**
test_image_create_invalid_url (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
test_image_create_invalidname (sdkwsgi.handlers.test_image.HandlersImageTest) ... ok
...................................................
test_getReservedMemSize_max_less_than_initial (test_makeVM.SMTMakeVMTestCase) ... ok
test_getVM_directory_py3 (test_vmUtils.SMTvmUtilsTestCase) ... ok

----------------------------------------------------------------------
Ran 12 tests in 0.004s

OK
_________________________________________________________________ summary __________________________________________________________________
  py36: commands succeeded
  congratulations :)

**Pull request merged**
