### PR TITLE
[master] improve deregister logic to avoid dirty data

### PR DESCRIPTION
**Pull request by SeanHQF**
There might be an exceptional case that the user deletes the VM
 from outside instead of zCC, then zCC DB still has its record which
 will become dirty data. This patch is to eliminate this dirty data.

### CODE REVIEW

**Comment by SeanHQF** [comment]
pep8 and ut has passed.

**Comment by SeanHQF** [comment]
@jichenjc pls review.

**Comment by qianxi2017** [comment]
lgtm

**Comment by jichenjc** [comment]
@bjhuangr please help to merge if it's ok to you
lgtm

**Comment by SeanHQF** [comment]
It's also tested in local env with script:
#!/usr/bin/env python
from zvmconnector import connector
import six
from nova import exception

conn = connector.ZVMConnector('9.152.85.144', port=8080, token_path='/etc/zvmsdk/token.dat')
results = conn.send_request('host_get_guest_list')

if results['overallRC'] != 0:
    print("zVM Cloud Connector request failed. Results: %(results)s",
                {'results': six.text_type(results)})
    raise exception.ZVMConnectorError(results=results)

print "Success! Result1: %s" % six.text_type(results)

port_macs = {'VSC1159A': '6e2ecc4f-14a2-4f33-9f12-5ac4a42f97e7' }
#results = conn.send_request('guest_register', 'fba', 'rhel7', '1', 'portttt')
results = conn.send_request('guest_register', 'fba', 'rhel7', '1', port_macs)

if results['overallRC'] != 0:
    print("zVM Cloud Connector request failed. Results: %(results)s",
                {'results': six.text_type(results)})
    raise exception.ZVMConnectorError(results=results)
print "Success! Result2: %s" % six.text_type(results)

results = conn.send_request('guest_deregister', 'fba')
if results['overallRC'] != 0:
    print("zVM Cloud Connector request failed. Results: %(results)s",
                {'results': six.text_type(results)})
    raise exception.ZVMConnectorError(results=results)

print "Success! Result3: %s" % six.text_type(results)

**Pull request merged**
