### PR TITLE
[master]change default value of timeout for waiting stop actions

### PR DESCRIPTION
**Pull request by SharpRazor**
Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

### CODE REVIEW

**Comment by SharpRazor** [comment]
@jichenjc @bjhuangr this is the new PR. please put your comments here.

**Comment by SharpRazor** [comment]
if apply this PR, the stop actions will try max 12 times before the VM in OFF status.
And the overall timeout should be about 120 seconds.

**Comment by jichenjc** [comment]
@SharpRazor please rebase the PR, then we can merge this

**Comment by SharpRazor** [comment]
> @SharpRazor please rebase the PR, then we can merge this

rebase done.

**Pull request merged**
