### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wlchurch**
Fix mistakes

### CODE REVIEW

**Comment by jichenjc** [comment]
@wlchurch thanks for the fixing, can you help to fix DCO first? Thanks

**Comment by wlchurch** [comment]
No idea how to fix DCO. I made the update through the web interface.

**Comment by wlchurch** [comment]
Signed-off-by: W Church <wlchurch@hotmail.com>

**Comment by jichenjc** [comment]
see https://github.com/openmainframeproject/python-zvm-sdk/pull/62/checks?check_run_id=381930473 for the info ...

**Comment by wlchurch** [comment]
I see that the DCO check failed. I do not have a cloned copy of the repository. I made the change through the website, and now do not see a way to sign off on the commit.

**Pull request closed without merging**
