### PR TITLE
Haoqf dereg master

### PR DESCRIPTION
**Pull request by SeanHQF**
This PR is for master branch and the related PR is https://github.com/openmainframeproject/python-zvm-sdk/pull/61

### CODE REVIEW

**Comment by jichenjc** [comment]
looks like there is a conflict, can you help to solve that?

**Comment by SeanHQF** [comment]
ok. I'll fix it.

**Comment by jichenjc** [comment]
@SeanHQF please fix conflicts otherwise you will get more and more conflicts

**Comment by SeanHQF** [comment]
@jichenjc I have submit the commits basing on the latest code and ut passed as attached. thanks
[utdereg-master.log](https://github.com/openmainframeproject/python-zvm-sdk/files/4222655/utdereg-master.log)

**Comment by SeanHQF** [comment]
@jichenjc can you please help to merge it and I have made all checks (pep8, ut, doc) passed locally by 'tox -v'?

**Comment by SeanHQF** [comment]
[tox-all.log](https://github.com/openmainframeproject/python-zvm-sdk/files/4224813/tox-all.log)

**Pull request merged**
