### PR TITLE
[Master] Modify the mount point of swap partition in guest.

### PR DESCRIPTION
**Pull request by wanxiangyuer**
1. rename the mount point of swap partition from /mnt/ephemeralxxxx to swap.

### CODE REVIEW

**Comment by wanxiangyuer** [comment]
The py27 test result:
image

The pep8 test result:
 [root@xyimgr77 python-zvm-sdk]# tox -v -epep8
using tox.ini: /root/python-zvm-sdk/tox.ini (pid 8274)
using tox-3.14.6 from /usr/local/lib/python3.6/site-packages/tox/__init__.py (pid 8274)
pep8 cannot reuse: no previous config /root/python-zvm-sdk/.tox/pep8/.tox-config1
pep8 create: /root/python-zvm-sdk/.tox/pep8
[8308] /root/python-zvm-sdk/.tox$ /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 pep8 >pep8/log/pep8-0.log
pep8 installdeps: flake8
[8315] /root/python-zvm-sdk$ /root/python-zvm-sdk/.tox/pep8/bin/pip install -U flake8 >.tox/pep8/log/pep8-1.log
pep8 develop-inst: /root/python-zvm-sdk
write config to /root/python-zvm-sdk/.tox/pep8/.tox-config1 as '9cf04510595b23664797abb327d98b49b001479f83d875adb17b7b2d012a83bc /usr/bin/python3\n3.14.6 0 1 0\n00000000000000000000000000000000 flake8'
[8323] /root/python-zvm-sdk$ /root/python-zvm-sdk/.tox/pep8/bin/pip install -U --exists-action w -e . >.tox/pep8/log/pep8-2.log
[8336] /root/python-zvm-sdk$ /root/python-zvm-sdk/.tox/pep8/bin/python -m pip freeze >.tox/pep8/log/pep8-3.log
pep8 installed: attrs==19.3.0,certifi==2020.4.5.1,chardet==3.0.4,entrypoints==0.3,flake8==3.7.9,idna==2.9,importlib-metadata==1.6.0,jsonschema==3.2.0,mccabe==0.6.1,netaddr==0.7.19,pycodestyle==2.5.0,pyflakes==2.1.1,PyJWT==1.7.1,pyrsistent==0.16.0,repoze.lru==0.7,requests==2.23.0,Routes==2.4.1,six==1.14.0,urllib3==1.25.8,WebOb==1.8.6,zipp==3.1.0,-e git+https://github.com/wanxiangyuer/python-zvm-sdk.git@36dc4d3b6aca01637d3f7203dd954827b9ea3c12#egg=zVMCloudConnector
pep8 run-test-pre: PYTHONHASHSEED='3528977992'
pep8 run-test: commands[0] | flake8
[8341] /root/python-zvm-sdk$ /root/python-zvm-sdk/.tox/pep8/bin/flake8
pep8 run-test: commands[1] | flake8 /root/python-zvm-sdk/scripts/sdkserver
[8356] /root/python-zvm-sdk$ /root/python-zvm-sdk/.tox/pep8/bin/flake8 scripts/sdkserver
__________________________________________________________________________ summary ___________________________________________________________________________
  pep8: commands succeeded
  congratulations :)

**Comment by jichenjc** [comment]
have you figure out the swap usage? only the mount point ?

**Comment by jichenjc** [comment]
please fix conflict then we can merge the code, thanks

**Comment by wanxiangyuer** [comment]
To verify the swap real function, I use dd if=/dev/zero of=/temp to consume Mem quickly. Before i run the command, 
```
[root@rhel77tst ~]# free -m
                     total        used        free      shared  buff/cache   available
Mem:           3847        1091         823           8        1932        2652
Swap:          1024           0        1024

[root@rhel77tst ~]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasda1     9.8G  1.4G  8.0G  15% /
```
After that:
```
[root@rhel77tst ~]# dd if=/dev/zero of=/temp
dd: writing to '/temp': No space left on device
17600353+0 records in
17600352+0 records out
9011380224 bytes (9.0 GB) copied, 54.8635 s, 164 MB/s

[root@rhel77tst ~]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasda1     9.8G  9.8G     0 100% /

[root@rhel77tst ~]# free -m
                     total        used        free      shared  buff/cache   available
Mem:           3847        1056          62           1        2729        2695
Swap:          1024          43         981
```
@jichenjc @dongyanyang

**Comment by jichenjc** [comment]
that seems right, thanks for the detailed info

can you help to solve the conflict so that we can merge this?

**Pull request merged**
