### PR TITLE
use jinja2 template to generate shell script

### PR DESCRIPTION
**Pull request by RollandXu**
Now we can use jinja2 template to generate a shell script, it easier maintenance than use python to generate many piece of shell codes.

### CODE REVIEW

**Comment by bjhuangr** [comment]
Does this change transparent to end user?

**Comment by RollandXu** [comment]
The end user can not use the templates directly, it transparent to end user. Those templates are currently only used for attach/detach volume and also don't need change the attach/detach volume inteface.

**Comment by jichenjc** [comment]
can you help to rebase this ? @RollandXu

**Comment by RollandXu** [comment]
> can you help to rebase this ? @RollandXu

OK, already rebased.

**Comment by dongyanyang** [comment]
@bjhuangr @jichenjc This is what I said about the jianjia2. It is not cherry-picked to 1.5.n. Does not affect function.

**Pull request merged**
