### PR TITLE
[master] Reserve FCP devices when deploying VMs

### PR DESCRIPTION
**Pull request by changzhi1990**
Reserve and unreserve FCP devices when deplying and deleting VMs.

### CODE REVIEW

**Comment by changzhi1990** [comment]
pep8 has passed:
image

py27 has passed:
image

**Comment by dongyanyang** [comment]
@jichenjc @SharpRazor pls help review this change. We didn't use the "reserve" field before, is there any special reason?

**Comment by jichenjc** [comment]
do we have any bug or additional info on the purpose of the PR?
I can guess the purpose but it would be better to have those in either a bug or commit msg

**Comment by changzhi1990** [comment]
> do we have any bug or additional info on the purpose of the PR?
> I can guess the purpose but it would be better to have those in either a bug or commit msg

https://github.ibm.com/zvc/planning/issues/1845

**Comment by changzhi1990** [comment]
Currently, we fail to deploy multi VMs at one time.

1. First, nova needs to get a "get_volume_connector" from the ZVM driver.
At the zvmsdk volume.py, "self.fcp_mgr.get_available_fcp" will allocate a available FCP list. At " get_available_fcp " function,
image

" self.db.get_from_assigner " will return none because there is no already existed FCP devices of the new assigner. So, the function "self.db.get_fcp_pair" will return a available FCP list.

image

This function will find a FCP list which not reserved ( reserved=0 ). Finally, will return a volume_connector.

2. While attaching a volume, at zvmsdk, the function " add_fcp_for_assigner ", will try to assign FCP devices to a specific user.
In this function, the function "self.db.assign" will operate the DB.
image


When we deploy VMs one by one, the procedure of the above steps are 1->2->1->2 ......
But when we deploy multi VMs at the same time, the procedure of the above steps are 1->1->2->2 .......

So, the zvmsdk will allocate the same FCP devices at step1.

How to resolve the problem?

At step1, add an "FCP reserve" step, at the zvmsdk, there are two functions can reserve the FCP device, one is "reserve" and the other one is "negation".
The function reserve will only update the "reserved" field to 1. And the function "negation" will change the "reserved" from 0 to 1 or from 1 to 0.

These two methods are both effective.

**Comment by SharpRazor** [comment]
@changzhi1990 Hi the negation is the method I wrote before, because I also want to use reserve field at that time. I wanted to use reserve as a lock.But it doesn't work for some cases. 
For example, we need attach more than one times for one VM. But the FCP devices is the same.
negation functions may cause fault.
So I sugguest not using negation function, you can design another function for your case.
This is a tricky area about reserve field and I sugguest full regression about volumes after your changes.

**Comment by dongyanyang** [comment]
@jichenjc take a look?

**Comment by jichenjc** [comment]
please help to solve the conflict

@dongyanyang @changzhi1990 you are aware the info provided by @SharpRazor ?

**Comment by changzhi1990** [comment]
> please help to solve the conflict
> 
> @dongyanyang @changzhi1990 you are aware the info provided by @SharpRazor ?

Yes, I'm using the reserve and the unreserve method, rather than negation method.

**Pull request merged**
