### PR TITLE
[Master] Provide the VM onboarding function in guest_register API

### PR DESCRIPTION
**Pull request by SeanHQF**
The current guest_register API in zCC is originated live migration actually and
it can't fulfill the requirement of onboarding although it intends to.
This PR is to retrofit it to be a general API which can fulfill both migration and onboarding's
requirement, and even future requirements as well.

This PR is for master branch and the related PR is https://github.com/openmainframeproject/python-zvm-sdk/pull/65

### CODE REVIEW

**Comment by jichenjc** [comment]
please fix the conflict.

**Comment by SeanHQF** [comment]
Ok, I'll resubmit it with change for @bjhuangr 's comment.

**Comment by jichenjc** [comment]
there are a lot of conflict, please update the conflict and please update the PR title
the PR title and commit message are helpful to review @SeanHQF

**Comment by SeanHQF** [comment]
> there are a lot of conflict, please update the conflict and please update the PR title
> the PR title and commit message are helpful to review @SeanHQF

Done except the conflicts. The major discussions are in the related PR https://github.com/openmainframeproject/python-zvm-sdk/pull/65, can you pls check that there?
And after those comments are addressed, I'll submit the code here with latest update.
thanks

**Comment by SeanHQF** [comment]
@jichenjc @bjhuangr Comments addressed (get_definition_info kept for I didn't find way to replace it), updated with master latest and all checks passed as attached (tox -v). Pls help to review and merge, thanks!
[master-all.log](https://github.com/openmainframeproject/python-zvm-sdk/files/4248323/master-all.log)

**Comment by SeanHQF** [comment]
@zhengxiaomei123 pls also help to review, thanks!

**Pull request merged**
